// packages/vanilla-w-react/src/all.global.ts
import * as Preact from 'react'
import * as PreactJSXRuntime from 'react/jsx-runtime'
import * as ProtectedApi from '@fullcalendar/react/protected-api'
import * as ProtectedStyles from '@fullcalendar/react/protected-styles'
import * as Interaction from '@fullcalendar/react/interaction'
import * as DayGrid from '@fullcalendar/react/daygrid'
import * as TimeGrid from '@fullcalendar/react/timegrid'
import * as List from '@fullcalendar/react/list'
import * as MultiMonth from '@fullcalendar/react/multimonth'

export * from '@fullcalendar/react/public-api'
export { Calendar } from './all'
export {
  Preact,
  PreactJSXRuntime,
  ProtectedApi,
  ProtectedStyles,
  Interaction,
  DayGrid,
  TimeGrid,
  List,
  MultiMonth,
}

// packages/web-component/src/all.global.ts
import * as Preact from 'preact'
import * as PreactJSXRuntime from 'preact/jsx-runtime'
import * as ProtectedApi from 'fullcalendar/protected-api'
import * as ProtectedStyles from 'fullcalendar/protected-styles'
import * as Interaction from 'fullcalendar/interaction'
import * as DayGrid from 'fullcalendar/daygrid'
import * as TimeGrid from 'fullcalendar/timegrid'
import * as List from 'fullcalendar/list'
import * as MultiMonth from 'fullcalendar/multimonth'
import { FullCalendarElement } from './all'
import './global-types'

// this is an IIFE file

globalThis.FullCalendarElement = FullCalendarElement
customElements.define('full-calendar', FullCalendarElement)

export * from 'fullcalendar/public-api'
export {
  Preact,
  PreactJSXRuntime,
  FullCalendarElement,
  ProtectedApi,
  ProtectedStyles,
  Interaction,
  DayGrid,
  TimeGrid,
  List,
  MultiMonth,
}
